use POKEMON
go
create procedure SP_GET_TRAINER_POKEMONS
	@trainer_id int
as
begin
	select	POKEMON_SPECIES.POKEMON_NAME,
			POKEMONS.POKEMON_NICKNAME,
			POKEMONS.HELD_ITEM_ID,
			POKEMONS.MOVE_1,
			POKEMONS.MOVE_2,
			POKEMONS.MOVE_3,
			POKEMONS.MOVE_4
	from POKEMONS,POKEMON_SPECIES,TRAINERS
	where	POKEMON_SPECIES.POKEMON_SPECIES_ID = POKEMONS.POKEMON_SPECIES_ID and
			POKEMONS.TRAINER_ID = TRAINERS.TRAINER_ID and
			TRAINERS.TRAINER_ID = @trainer_id
end
